name: ampere-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pyyaml
  - scikit-image
  - cudatoolkit
  - pytorch=*=cuda*
  - torchvision=*=cuda*
  - tensorflow=2.*.*=cuda*
#  - tf_slim  # including this causes python, TF to be quite old versions
  - mmdet
  - mmcv-full<=1.7.0
  - hdf5storage
  - keras-applications
  - easydict
  - pandas
  - tqdm
  - ruamel.yaml
  - shapely
  - pip
  - pip:
    - chumpy
    - xtcocotools
    - mmpose==0.29.0
    - tf_slim
    
